### PR TITLE
Update Libretranslate deployment

### PR DESCRIPTION
**Pull request by NeonDaniel**
# Description
Update libretranslate deployment to set `ARGOS_PACKAGE_INDEX` envvar

# Issues

# Other Notes
These changes have not been recently tested

### CODE REVIEW

**Review by mikejgray — APPROVED** [review]
LGTM but I'm not exactly sure what this environment variable does. Looks like action versions need to be updated as well

**Comment by NeonDaniel** [comment]
> LGTM but I'm not exactly sure what this environment variable does. Looks like action versions need to be updated as well

The envvar is pinning a specific commit in [argospm-index](https://github.com/argosopentech/argospm-index/). I don't know the exact cause for the startup error, but it appeared to be connected to a change there and our solution when this was originally opened was to pin the known working commit in the added envvar

**Review by mikejgray — APPROVED** [review]
Code looks good, I don't have a stable Diana instance running anymore. Is this deployed somewhere that I can validate it works as expected?

**Comment by NeonDaniel** [comment]
> Code looks good, I don't have a stable Diana instance running anymore. Is this deployed somewhere that I can validate it works as expected?

Yeah, currently deployed to https://libretranslate.neonaialpha.com

**Pull request merged**
